// COPYRIGHT Dassault Systemes 2026
//===================================================================
//
// IdentityCard.h
// Supplies the list of prerequisite components for framework Hello
//
//===================================================================
//
// Usage notes:
//   For every prereq framework FW, use the syntax:
//   AddPrereqComponent ("FW", Public);
//
//===================================================================
//
//  Sep 2026  Creation: Code generated by the CAA wizard  B
//===================================================================
// DO NOT EDIT :: THE CAA2 WIZARDS WILL ADD CODE HERE
AddPrereqComponent("System", Protected);
AddPrereqComponent("Dialog", Public);
AddPrereqComponent("ApplicationFrame", Public);
AddPrereqComponent("ProductStructure", Public);
AddPrereqComponent("DraftingInterfaces", Public);
AddPrereqComponent("ObjectModelerBase", Public);
AddPrereqComponent("PartInterfaces", Public);
AddPrereqComponent("SketcherInterfaces", Public);
AddPrereqComponent("MecModInterfaces", Public);
