# COPYRIGHT Dassault Systemes 2026
#======================================================================
# Imakefile for module TestModule.m
#======================================================================
#
#  Sep 2026  Creation: Code generated by the CAA wizard  B
#======================================================================
#
# SHARED LIBRARY 
#
BUILT_OBJECT_TYPE=SHARED LIBRARY 
 
# DO NOT EDIT :: THE CAA2 WIZARDS WILL ADD CODE HERE
WIZARD_LINK_MODULES = JS0GROUP \
JS0GROUP JS0FM
# END WIZARD EDITION ZONE

LINK_WITH = DraftingPubIDL CATInfInterfaces CATMathematics CATVisualization CATOmnMain CATProductStructure1 CATApplicationFrame CATObjectModelerBase AC0SPBAS DraftingItfCPP CATPartInterfaces CATSketcherInterfaces CATMecModInterfaces $(WIZARD_LINK_MODULES) DI0PANV2

# System dependant variables
#
OS = AIX
#
OS = HP-UX
#
OS = IRIX
#
OS = SunOS
#
OS = Windows_NT
