set ADSK_CLM_WPAD_PROXY_CHECK=FALSE
set ALLUSERSPROFILE=C:\ProgramData
set APPDATA=C:\Users\A\AppData\Roaming
set BLD_HOST_OS=win_b64
set CATEnvPath=C:\ProgramData\DassaultSystemes\CATEnv
set CatiaInstallPath=C:\Program Files\Dassault Systemes\B21_RADE
set CommonProgramFiles=C:\Program Files (x86)\Common Files
set CommonProgramFiles(x86)=C:\Program Files (x86)\Common Files
set CommonProgramW6432=C:\Program Files\Common Files
set COMPUTERNAME=DESKTOP-0E778PL
set ComSpec=C:\Windows\system32\cmd.exe
set CorbaCppBuildROOT_PATH=\\ds\dsy\iona\Orbix3.3\win_b64
set CorbaCppROOT_PATH=\\ds\dsy\iona\Orbix3.3\win_b64
set CorbaJavaROOT_PATH=\\ds\dsy\iona\Orbix3.3\win_b64
set CSCSkipTestOfMapFileValidity=1
set CSIDL_COMMON_APPDATA=C:\ProgramData
set DriverData=C:\Windows\System32\Drivers\DriverData
set DSLICENSING=DSLS
set DSXDEVVISUALCOMPILERVERSION=1.0-1.4
set getRADE=C:\Users\A\AppData\Local\Temp\getRADE18540.bat
set HOMEDRIVE=C:
set HOMEPATH=\Users\B
set INCLUDE=C:\Program Files (x86)\Microsoft Visual Studio 9.0\VC\include;C:\Program Files (x86)\Microsoft Visual Studio 9.0\VC\atlmfc\include;C:\Program Files\Microsoft SDKs\Windows\v6.0A\include;C:\Program Files\Dassault Systemes\B21_RADE\intel_a\.\tools\include\win_b64;C:\Program Files\Dassault Systemes\B21_RADE\intel_a\.\tools\include
set JLMDeployROOT_PATH=C:\Program Files\Dassault Systemes\B21_RADE\intel_a\.\jlm\jlmdeploy65
set LIB=C:\Program Files (x86)\Microsoft Visual Studio 9.0\VC\lib\amd64;C:\Program Files (x86)\Microsoft Visual Studio 9.0\VC\atlmfc\lib\amd64;C:\Program Files\Microsoft SDKs\Windows\v6.0A\lib\x64;C:\Windows\Microsoft.NET\Framework64\v3.5;C:\Program Files\Reference Assemblies\Microsoft\Framework\v3.5;C:\Program Files\Reference Assemblies\Microsoft\Framework\v3.0;C:\Windows\Microsoft.NET\Framework64\v2.0.50727
set LOCALAPPDATA=C:\Users\A\AppData\Local
set LOGONSERVER=\\DESKTOP-0E778PL
set mkcsbuild=502111104
set mkcsClientMode=1
set mkcsINSTALL_PATH=C:\Program Files\Dassault Systemes\B21_RADE
set mkcsOS_Buildtime=win_b64
set mkcsOS_NAME=Windows_NT
set mkcsOS_Runtime=intel_a
set mkcsROOT_PATH=C:\Program Files\Dassault Systemes\B21_RADE\intel_a
set mkcsSHLIB_NAME=PATH
set mkcsSHLIB_PATH=C:\Program Files\Dassault Systemes\B21_RADE\intel_a\code\bin
set mkcsVERSION=5.21.0.11104 (built Thu, Apr 14, 2011 at 20:00)
set MkmkADDON_INCLUDE=C:\Program Files (x86)\Microsoft Visual Studio 9.0\VC\include;C:\Program Files (x86)\Microsoft Visual Studio 9.0\VC\atlmfc\include;C:\Program Files\Microsoft SDKs\Windows\v6.0A\include;C:\Program Files\Dassault Systemes\B21_RADE\intel_a\.\tools\include\win_b64;C:\Program Files\Dassault Systemes\B21_RADE\intel_a\.\tools\include
set MkmkADDON_LEVEL=MK_CATIAVER=5 MK_BITMODE=64 MK_MSCVER=1500 MK_IFVER=1001011 MK_ORBIXCPP33 MK_ORBIXJAVA33
set MkmkADDON_LIB=C:\Program Files (x86)\Microsoft Visual Studio 9.0\VC\lib\amd64;C:\Program Files (x86)\Microsoft Visual Studio 9.0\VC\atlmfc\lib\amd64;C:\Program Files\Microsoft SDKs\Windows\v6.0A\lib\x64;C:\Windows\Microsoft.NET\Framework64\v3.5;C:\Program Files\Reference Assemblies\Microsoft\Framework\v3.5;C:\Program Files\Reference Assemblies\Microsoft\Framework\v3.0;C:\Windows\Microsoft.NET\Framework64\v2.0.50727
set MkmkADDON_PATH=C:\Program Files (x86)\Microsoft Visual Studio 9.0\VC\bin\amd64;C:\Program Files\Microsoft SDKs\Windows\v6.0A\bin\x64;C:\Windows\Microsoft.NET\Framework64\v3.5;C:\Program Files\Reference Assemblies\Microsoft\Framework\v3.5;C:\Program Files\Reference Assemblies\Microsoft\Framework\v3.0;C:\Windows\Microsoft.NET\Framework64\v2.0.50727;C:\Program Files\Dassault Systemes\B21_RADE\intel_a\code\command
set MkmkBAD_MINITFLEVEL=4
set mkmkbuild=502111104
set MkmkDELPHI50Internal=yes
set MkmkDictionary_PATH=C:\Program Files\Dassault Systemes\B21_RADE\intel_a\code\dictionary
set MkmkExternalDS=External
set MkmkIC_PATH=C:\Program Files\Dassault Systemes\B21_RADE\intel_a\code\productIC
set MkmkIF101Internal=101.011
set MkmkINSTALL_PATH=C:\Program Files\Dassault Systemes\B21_RADE
set MkmkJDK16Internal=0_14
set MkmkMsgCatalog_PATH=C:\Program Files\Dassault Systemes\B21_RADE\intel_a\resources\msgcatalog
set MkmkMSNET30DIR=C:\Program Files\Reference Assemblies\Microsoft\Framework\v3.0
set MkmkMSNET35DIR=C:\Program Files\Reference Assemblies\Microsoft\Framework\v3.5
set MkmkMSPSDKDIR=C:\Program Files\Microsoft SDKs\Windows\v6.0A
set MkmkMSVCDIR=C:\Program Files (x86)\Microsoft Visual Studio 9.0\VC
set MkmkMSVCSHARPDIR=C:\Windows\Microsoft.NET\Framework64\v3.5
set MkmkMSVJSHARPDIR=C:\Windows\Microsoft.NET\Framework64\v2.0.50727
set MkmkMSVSBINDIR=C:\Program Files (x86)\Microsoft Visual Studio 9.0\Common7\IDE
set MkmkMSVSTOOLSBINDIR=C:\Program Files (x86)\Microsoft Visual Studio 9.0\Common7\Tools\Bin
set MkmkOS_BitMode=64
set MkmkOS_Buildtime=win_b64
set MkmkOS_DOC=DOC
set MkmkOS_NAME=Windows_NT
set MkmkOS_Runtime=intel_a
set MkmkOS_Type=Windows
set MkmkOS_VAR=win_b64
set MkmkPATH4TOOLS=C:\Program Files (x86)\Microsoft Visual Studio 9.0\VC\bin\amd64;C:\Program Files\Microsoft SDKs\Windows\v6.0A\bin\x64;C:\Windows\Microsoft.NET\Framework64\v3.5;C:\Program Files\Reference Assemblies\Microsoft\Framework\v3.5;C:\Program Files\Reference Assemblies\Microsoft\Framework\v3.0;C:\Windows\Microsoft.NET\Framework64\v2.0.50727;C:\Program Files (x86)\Microsoft Visual Studio 9.0\Common7\IDE;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0;C:\Program Files\dotnet;C:\Program Files\NVIDIA Corporation\NVIDIA App\NvDLISR;C:\Program Files\Git\cmd;C:\Users\A\AppData\Local\nvm;C:\Program Files\nodejs;C:\Program Files (x86)\Microsoft SQL Server\90\Tools\binn;E:\Workshop\Catia_Caa_Test\win_b64\code\bin;C:\Users\A\AppData\Local\Microsoft\WindowsApps;C:\Users\A\AppData\Local\Programs\Microsoft VS Code\bin;C:\Users\A\AppData\Roaming\npm;C:\Program Files\Dassault Systemes\B21_RADE\intel_a\TCK\command
set MkmkReffiles_PATH=C:\Program Files\Dassault Systemes\B21_RADE\intel_a\reffiles
set MkmkRMSSDK_PATH=C:\Program Files\Dassault Systemes\B21_RADE\intel_a\.\rms\rmssdksp2
set MkmkROOTINSTALL_PATH=C:\Program Files\Dassault Systemes\B21_RADE\intel_a
set MkmkROOT_PATH=C:\Program Files\Dassault Systemes\B21_RADE\intel_a
set MkmkSHLIB_NAME=PATH
set MkmkSHLIB_PATH=C:\Program Files\Dassault Systemes\B21_RADE\intel_a\code\bin
set MkmkTOOLSINCLUDE_PATH=C:\Program Files\Dassault Systemes\B21_RADE\intel_a\.\tools\include\win_b64;C:\Program Files\Dassault Systemes\B21_RADE\intel_a\.\tools\include
set MkmkTOOLSLIB_PATH=C:\Program Files\Dassault Systemes\B21_RADE\intel_a\.\tools\lib
set MkmkVERSION=5.21.0.11104 (built Thu, Apr 14, 2011 at 20:00)
set MkmkVERSIONINFO=NO
set MkmkVS90Internal=yes
set MkmkXMLMANIFEST=NO
set Mkmk_Modifier=1578
set Mkmk_Modifier_BAD=16
set MKMK_USEPRECOMPIL=yes
set MkodtOS_Runtime=win_b64
set MK_DEVNULL=NUL
set MK_SEPARATOR=;
set MK_TEMPDIR=C:\Users\A\AppData\Local\Temp
set NO_LOCAL_DEFINITION_FOR_IID=yes
set NUMBER_OF_PROCESSORS=16
set NVM_HOME=C:\Users\A\AppData\Local\nvm
set NVM_SYMLINK=C:\nvm4w\nodejs
set OneDrive=C:\Users\A\OneDrive
set OneDriveConsumer=C:\Users\A\OneDrive
set OS=Windows_NT
set PATH=C:\Program Files (x86)\Microsoft Visual Studio 9.0\VC\bin\amd64;C:\Program Files\Microsoft SDKs\Windows\v6.0A\bin\x64;C:\Windows\Microsoft.NET\Framework64\v3.5;C:\Program Files\Reference Assemblies\Microsoft\Framework\v3.5;C:\Program Files\Reference Assemblies\Microsoft\Framework\v3.0;C:\Windows\Microsoft.NET\Framework64\v2.0.50727;C:\Program Files (x86)\Microsoft Visual Studio 9.0\Common7\IDE;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0;C:\Program Files\dotnet;C:\Program Files\NVIDIA Corporation\NVIDIA App\NvDLISR;C:\Program Files\Git\cmd;C:\Users\A\AppData\Local\nvm;C:\Program Files\nodejs;C:\Program Files (x86)\Microsoft SQL Server\90\Tools\binn;E:\Workshop\Catia_Caa_Test\win_b64\code\bin;C:\Users\A\AppData\Local\Microsoft\WindowsApps;C:\Users\A\AppData\Local\Programs\Microsoft VS Code\bin;C:\Users\A\AppData\Roaming\npm;C:\Program Files\Dassault Systemes\B21_RADE\intel_a\TCK\command;C:\Program Files\Dassault Systemes\B21_RADE\intel_a\code\command;C:\Program Files\Dassault Systemes\B21_RADE\intel_a\code\command
set PATHEXT=.COM;.EXE;.BAT;.CMD;.VBS;.VBE;.JS;.JSE;.WSF;.WSH;.MSC
set PROCESSOR_ARCHITECTURE=AMD64
set PROCESSOR_ARCHITEW6432=AMD64
set PROCESSOR_IDENTIFIER=Intel64 Family 6 Model 151 Stepping 2, GenuineIntel
set PROCESSOR_LEVEL=6
set PROCESSOR_REVISION=9702
set ProgramData=C:\ProgramData
set ProgramFiles=C:\Program Files (x86)
set ProgramFiles(x86)=C:\Program Files (x86)
set ProgramW6432=C:\Program Files
set PROMPT=$P$G
set PSModulePath=C:\Program Files\WindowsPowerShell\Modules;C:\Windows\system32\WindowsPowerShell\v1.0\Modules
set PUBLIC=C:\Users\Public
set RADECATSettingPath=C:\Users\A\AppData\Roaming\DassaultSystemes\CATSettings\RADE
set RELEASEMANAGER_PATH=C:\Program Files\Dassault Systemes\B21_RADE\intel_a
set rtcode=0
set SESSIONNAME=Console
set SystemDrive=C:
set SystemRoot=C:\Windows
set TCKHelp=-
set TCKOS_Runtime=intel_a
set TCK_DATE=2026/09/05-23:52:40
set TCK_ID=V5R21_B21
set TCK_INSTALL_PATH=C:\Program Files\Dassault Systemes\B21_RADE
set TCK_LOCAL_INFO=C:\Program Files (x86)
set TCK_NAME=V5R21_B21
set TCK_NO_SERVER=true
set TCK_ROOT_PATH=C:\Program Files\Dassault Systemes\B21_RADE\intel_a
set TCK_TMP_FILE=C:\Users\A\AppData\Local\Temp\tckexec__B_27775.bat
set TEMP=C:\Users\A\AppData\Local\Temp
set TMP=C:\Users\A\AppData\Local\Temp
set USERDOMAIN=DESKTOP-0E778PL
set USERDOMAIN_ROAMINGPROFILE=DESKTOP-0E778PL
set USERNAME=B
set USERPROFILE=C:\Users\A
set VBTtmp=C:\Users\A\AppData\Local\Temp
set VisualStudioDir=C:\Users\A\Documents\Visual Studio 2008
set VS90COMNTOOLS=C:\Program Files (x86)\Microsoft Visual Studio 9.0\Common7\Tools\
set WecVersionForRosebud.3B7C=2
set windir=C:\Windows
set _tck_exec=OK
set __COMPAT_LAYER=ElevateCreateProcess
set MkmkPATH4TOOLS=%MkmkPATH4TOOLS:E:\Workshop\Catia_Caa_Test\win_b64\code\bin=D:\Workshop\Catia_Caa_Test\win_b64\code\bin%
set PATH=%PATH:E:\Workshop\Catia_Caa_Test\win_b64\code\bin=D:\Workshop\Catia_Caa_Test\win_b64\code\bin%
